### ISSUE TITLE
Parser generation for test language 'Bug297105testlanguage' fails

### ISSUE THREAD

**Issue by sailingKieler** [eclipse/xtext-idea#12]
The generation of the `org.eclipse.xtext.core.idea.tests/src-gen/org/eclipse/xtext/parser/terminalrules/idea/parser/antlr/internal/PsiInternalBug297105TestLanguageLexer.java` and `...Parser.java` by ANTLR fails with the error

```
error(201): ../org.eclipse.xtext.tests/../../xtext-idea/org.eclipse.xtext.core.idea.tests/src-gen/org/eclipse/xtext/parser/terminalrules/idea/parser/antlr/internal/PsiInternalBug297105TestLanguage.g:139:2: The following alternatives can never be matched: 2
```

The input grammar has been generated with the new grammar generation fragment `org.eclipse.xtext.xtext.generator.idea.parser.antlr.XtextAntlrIDEAGeneratorFragment`

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
