### ISSUE TITLE
Web Editor Not working

### ISSUE THREAD

**Issue by ptyagi108** [eclipse/xtext-idea#17]
I  am using xtext 2.9.2 and intellj idea 2016.2.5 and i followed the steps given in https://blogs.itemis.com/en/get-started-with-xtext-and-intellij-idea-in-5-minutes.

After running target jettyRun successfully ,I am not getting cursor in web editor, so I am not able to enter any text in the web editor.I have attached the screenshot of the web Editor Screen.
![dsl web editor](https://cloud.githubusercontent.com/assets/3337154/20759334/b13c1be2-b742-11e6-97aa-26d61a2ef8e3.png)

**My DSL has following Grammer:**

grammar org.xtext.example.mydsl.IntegrationDsl with org.eclipse.xtext.common.Terminals

generate integrationDsl "http://www.xtext.org/example/mydsl/IntegrationDsl"

File :
	(imports+=Import)*
	(interceptorDecls+=GlobalInterceptorDecl)*
	(routes+=Route)*
	(interceptorDefs+=InterceptorChainDef)*
;

Route :
	"route" name=ID from=From interceptors=(Interceptors)? "{" (target+=ToTarget)+ "}"
;

Import :
	"import" (location=STRING)
;

GlobalInterceptorDecl :
	"global" "interceptors" (interceptorName=[InterceptorChainDef])
;

InterceptorChainDef :
	"interceptor" name=ID "{"
	(chain+=BeanExpr)+
	"}"
;

Interceptors :
	"interceptors" "(" (interceptorName+=[InterceptorChainDef])+ ")"
;

From :
	"from" uri=STRING
;

To :
	"to" uri=STRING
;

PatternExpr :
	Choice | Recipients | Pipeline | Filter | Splitter | Resequencer | Transformer | DynamicRecipients
;

ProcessExpr :
	PatternOrBeanExpr
;

PatternOrBeanExpr :
	BeanExpr | PatternExpr
;

BeanExpr :
	BEAN id=ID (method=ID)?
;

SimplePattern :
	(interceptors=Interceptors)? "{"
	(actions+=ActionStatement)*
	(targets+=ToTarget)+
	(properties=PropertiesBlock)?
	"}"
;

ActionStatement :
	SetHeaderAction | SetBodyAction | "convert" ConvertBodyAction
;

SetHeaderAction :
	"header" header=STRING "=" (value=Expression)
;

SetBodyAction :
	"body" "=" (value=Expression)
;

ConvertBodyAction :
	ConvertBodyWithAction | ConvertBodyToAction
;

ConvertBodyWithAction :
	"with" BeanExpr
;

ConvertBodyToAction :
	"to" (type=STRING)
;

Transformer :
	"transformer" (Interceptors)? "{"
	beanref=BeanExpr
	(target+=ToTarget)+
	"}"
;

Choice :
	"choice" (Interceptors)? "{"
	(when+=WhenClause)*
	(otherwise=OtherwiseClause)?
	"}"
;

Recipients :
	"recipients" body=SimplePattern
;

DynamicRecipients :
	"dynamic" "recipients" body=Expression
;

Pipeline :
	"pipeline" body=SimplePattern
;

Filter :
	"filter" expr=Expression body=SimplePattern
;

Splitter :
	"splitter" expr=Expression body=SimplePattern
;

Resequencer :
	"resequence" expr=Expression body=SimplePattern
;

WhenClause :
	"when" expr=Expression "{"
	(target+=ToTarget)+
	"}"
;

OtherwiseClause :
	"otherwise" "{" target=ToTarget "}"
;

Expression :
	lang=ID "(" value=ExpressionValue ")" | STRING
;

ExpressionValue :
	value=STRING
;

PropertiesBlock :
	"properties" "{"
	(properties+=PropertyDef)+
	"}"
;

PropertyDef :
	name=SCOPED_ID "=" value=STRING
;

ToTarget :
	To | ProcessExpr | Fault
;

Fault :
	"fault" STRING
;

SCOPED_ID :
	ID ("." ID)*
;

BEAN:  "bean";

**Below are the logs of my jettyRun:**

8:31:51 PM: Executing external task 'jettyRun'...
:EBIDsl:generateXtextLanguage UP-TO-DATE
:EBIDsl:generateXtext UP-TO-DATE
:EBIDsl:compileJava UP-TO-DATE
:EBIDsl:processResources UP-TO-DATE
:EBIDsl:classes UP-TO-DATE
:EBIDsl:jar UP-TO-DATE
:EBIDsl.ide:generateXtext UP-TO-DATE
:EBIDsl.ide:compileJava UP-TO-DATE
:EBIDsl.ide:processResources UP-TO-DATE
:EBIDsl.ide:classes UP-TO-DATE
:EBIDsl.ide:jar UP-TO-DATE
:EBIDsl.web:generateXtext UP-TO-DATE
:EBIDsl.web:compileJava UP-TO-DATE
:EBIDsl.web:processResources UP-TO-DATE
:EBIDsl.web:classes UP-TO-DATE
[main] INFO org.eclipse.jetty.util.log - Logging initialized @7718ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.3.8.v20160314
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@57baeedf{/,[file:///C:/Projects/EBIDsl/EBIDsl.parent/EBIDsl.web/src/main/webapp/, jar:file:///C:/Users/pramod_kumar_tyagi/.gradle/caches/modules-2/files-2.1/org.webjars/jquery/2.2.3/19d1bfa1b3b44d9ec66d3b672bcd26b470185708/jquery-2.2.3.jar!/META-INF/resources, jar:file:///C:/Users/pramod_kumar_tyagi/.gradle/caches/modules-2/files-2.1/org.webjars/requirejs/2.2.0/309f64b8d819823d40f9515e1bf6c4e189196687/requirejs-2.2.0.jar!/META-INF/resources, jar:file:///C:/Users/pramod_kumar_tyagi/.gradle/caches/modules-2/files-2.1/org.webjars/ace/1.2.2/d198ebab4e5a6f515ce2d9243f3ecc16a09f4fb6/ace-1.2.2.jar!/META-INF/resources, jar:file:///C:/Users/pramod_kumar_tyagi/.gradle/caches/modules-2/files-2.1/org.eclipse.xtext/org.eclipse.xtext.web/2.9.2/bce5ce569e3eba7458f8b0e0154f36afc781394b/org.eclipse.xtext.web-2.9.2.jar!/META-INF/resources],AVAILABLE}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@78c03f1f{HTTP/1.1,[http/1.1]}{localhost:8080}
[main] INFO org.eclipse.jetty.server.Server - Started @29646ms
[main] INFO org.xtext.example.mydsl.web.ServerLauncher - Server started http://localhost:8080/...
[Thread-8] INFO org.xtext.example.mydsl.web.ServerLauncher - Press enter to stop the server...
[Thread-8] WARN org.xtext.example.mydsl.web.ServerLauncher - Console input is not available. In order to stop the server, you need to cancel process manually.

**Comment by akosyakov** [comment]
@ptyagi108 Please try with the latest released Xtext (2.10) and with Eclipse. If it does not help, please look for errors/warnings in the browser log.

**Comment by ptyagi108** [comment]
@akosyakov I have not yet tried your suggestion with the latest released Xtext (2.10) and with Eclipse. But with  xtext 2.9.2 and intellj idea 2016.2.5 , below are the console logs from browser..Any suggestions..
![dsl_error](https://cloud.githubusercontent.com/assets/3337154/20823114/4bd71f14-b877-11e6-8cd1-3c0b4d5e70b7.png)

**Comment by ptyagi108** [comment]
@akosyakov Just to add one more point  ,in order to use 2.9.2 I have following entries in my build.gradle

subprojects {
	ext.xtextVersion = '2.9.2'
	repositories {
		jcenter()
	}

**Comment by cdietrich** [comment]
did you workaround the xtext-web bug https://github.com/eclipse/xtext-web/issues/5
by adding the following to the module

```
def void configureIPreferenceValuesProvider(Binder binder) {
	binder.bind(IPreferenceValuesProvider).annotatedWith(FormatterPreferences).to(FormatterPreferenceValuesProvider)
}
```

**Comment by ptyagi108** [comment]
I retried with version 2.10.0 and Intellij Idea , Cursor seems to work now and I am getting syntax highlighting too , but auto suggest/ content assist does not seem to work still.Below is the snapshot of errors i am getting..

![image](https://cloud.githubusercontent.com/assets/3337154/20827512/85313a4e-b898-11e6-90c6-e97012be7a0d.png)

**Comment by cdietrich** [comment]
well the first problem might that the server wont really start cause of the issue above.
did you call the gradlew jettyRun from command line and get the same?

**Comment by ptyagi108** [comment]
@cdietrich I think what you said is right , it is related to xtext-web bug eclipse/xtext-web#5(https://github.com/eclipse/xtext-web/issues/5). 

which file  should I add ,

def void configureIPreferenceValuesProvider(Binder binder) {
	binder.bind(IPreferenceValuesProvider).annotatedWith(FormatterPreferences).to(FormatterPreferenceValuesProvider)
}


**Below are my error logs:**
[qtp109961541-10] WARN org.eclipse.jetty.servlet.ServletHandler - /xtext-service/update
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.eclipse.xtext.preferences.IPreferenceValuesProvider annotated with @org.eclipse.xtext.formatting2.FormatterPreferences() was bound.
  while locating org.eclipse.xtext.preferences.IPreferenceValuesProvider annotated with @org.eclipse.xtext.formatting2.FormatterPreferences()
    for field at org.eclipse.xtext.web.server.XtextServiceDispatcher.formatterPreferencesProvider(XtextServiceDispatcher.java:98)
  while locating org.eclipse.xtext.web.server.XtextServiceDispatcher

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eclipse.xtext.web.servlet.XtextServlet.getService(XtextServlet.java:162)
	at org.eclipse.xtext.web.servlet.XtextServlet.doPut(XtextServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at org.eclipse.xtext.web.servlet.XtextServlet.service(XtextServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
[qtp109961541-14] WARN org.eclipse.jetty.servlet.ServletHandler - /xtext-service/update

**Comment by cdietrich** [comment]
add it to yourdslwebmodule

**Comment by ptyagi108** [comment]
After adding 

def void configureIPreferenceValuesProvider(Binder binder) {
binder.bind(IPreferenceValuesProvider).annotatedWith(FormatterPreferences).to(FormatterPreferenceValuesProvider)
}

My error is gone except for one exception ,

![image](https://cloud.githubusercontent.com/assets/3337154/20858780/f1f574d0-b972-11e6-90c9-1f14fdf4765d.png)

**Comment by ptyagi108** [comment]
I am trying following in my web editor , but somehow code assist/completion is not working , any idea?

![image](https://cloud.githubusercontent.com/assets/3337154/21094560/8252d64c-c07d-11e6-8b69-2b05a1ea1e28.png)

**Comment by cdietrich** [comment]
is content assist implemented for the stuff you are searching for? did you try to debug IdeContentProposalProvider?

**Comment by ptyagi108** [comment]
I did not implement any content assist , I was assuming that based on my grammer the web editor can suggest me with content . I followed the steps given in blog,

https://blogs.itemis.com/en/get-started-with-xtext-and-intellij-idea-in-5-minutes

**Comment by cdietrich** [comment]
yes but your grammar is different, thus it is important how your grammar looks like and at which places you invoke content assist. unfortunately the default in standalone/web is not as good as in eclipse

**Comment by ptyagi108** [comment]
@cdietrich 
First of all I would like to thank whole xtext team for their prompt help ..xtext team has given wonderful tool for DSL and made our life much easier...

I am struggling with content assist .. so i decided to run gradle target **_runIdea_** again ...what i see is an error in my intellij Idea console ..

**RuntimeException: Error during auto build.: java.io.IOException: Invalid file name: ':'** 

I saw the workaround for the same in bug entry 
_https://bugs.eclipse.org/bugs/show_bug.cgi?id=490190_

where you mentioned ...

_it seems there is actually a workaround
if you go to the project structure dialog
and there to facets
for the xtend facet there are outputfolders to be defined
file there is a C:/users/..../xtend-gen
replace this by 
xtend-gen only_

I could not really understand the work around , where i need to make changes...can u pls help me with this...

see my ide screenshot of project below..

![image](https://cloud.githubusercontent.com/assets/3337154/21179500/6069907c-c21a-11e6-8598-bdb9971fa4ed.png)

**Comment by ptyagi108** [comment]
@cdietrich I have two facetsclass  file in my project ...
_IntegrationDslFacetConfiguration
IntegrationDslFacetType_
But i did not find any place to mention output folders to be defind as mentioned in workaround for bug 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490190...

![image](https://cloud.githubusercontent.com/assets/3337154/21179772/8b037612-c21b-11e6-97a6-5f2e25eea187.png)

**Comment by cdietrich** [comment]
hi,

unfortunately i am too idea nooby and it is too long ago to have any idea

**Comment by cdietrich** [comment]
p.s.: does it work if you change the facet value in the facet editor?

**Comment by ptyagi108** [comment]
@cdietrich not sure where is facet editor in intellij idea...however just one question..

I am facing these issues with intellij idea...but i think intellij idea is currently supported IDE for XTEXT...and xtext has dumped eclipse in favour of intellij idea. see thread.. http://www.theserverside.com/discussions/thread.tss?thread_id=77270

can you please suggest me which IDE (Intellij Idea or Eclipse) is better supported in xtext..so that i can switch to eclipse if that helps me ..i need web editor for my DSL working with content assist. and i am running into these problems with intellij idea..if the eclipse is way to go can you please suggest me place to start ...

**Comment by cdietrich** [comment]
no the idea support is still very pure (and there is no developer actively working on it) and eclipse (and in future language server protocol) the way to do.
thus i recommend you to do the xtext/xtend development in eclipse

**Comment by cdietrich** [comment]
p.s. and i dont see here xtext is mentioned in the the server side thread

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
