### ISSUE TITLE
IDEA plugin manager cannot download Xtext

### ISSUE THREAD

**Issue by EricSalemi** [eclipse/xtext-idea#23]
I'm currently working with IDEA 2016.3.1 on a Windows 7 64-bit machine.

If I go to the plugin manager and look for XText related plugins I find:

XText 2.10.0
XText IDEA Core 2.10.0
XTend Support 2.10.0

None of these can be installed as IDEA simply timeouts. Other plugins can be installed without problems. IDEA spits out the following message after the timeout:

"Plugin Xtext IDEA Core was not installed: Cannot download 'https://download.eclipse.org/modeling/tmf/xtext/idea/2.10.0/org.eclipse.xtext.idea-2.10.0.zip': connect timed out"

This URL is currently not downloadable wit Mozilla Firefox or Google Chrome.

However, the non-secure version (http:// i.s.o https://) can be downloaded.

It seems that the the problem is either:

1) Eclipse download servers do not support HTTPS request (or it is broken)
2) We gave wrong URLS to the JetBrains guys

In any case, this is really bad for the promotion of XText on the IDEA platform.

**Comment by dhuebner** [comment]
@EricSalemi I'm quite sure it used to work before. I opened a bug in eclipse bugzilla let see what they say.

**Comment by dhuebner** [comment]
@EricSalemi And as I can see from https://plugins.jetbrains.com/update/index?pr=idea&updateId=26093 the URL we setup is http://

So it looks like the Jetbrains problem

**Comment by Treverix** [comment]
If all fails, we can always grab the three plugins from jetbrains plugins site install them 'from disk'. This is what I usually do, when intellijs plugin manager isn't cooperating.

They can be found here, near the end of the list: [https://plugins.jetbrains.com/idea/category/48-languages](https://plugins.jetbrains.com/idea/category/48-languages)

**Comment by sh1ftchg** [comment]
Manually add the repository.

http://download.eclipse.org/modeling/tmf/xtext/idea/2.10.0/updatePlugins.xml

@dhuebner AFAIK Jetbrains only supports secure redirection. Redirecting from the secure repository to an insecure eclipse hosted one probably won't work.

**Comment by wheelerlaw** [comment]
One of the support reps from JetBrains suggested changing this setting:
![image](https://user-images.githubusercontent.com/3081566/38152746-223f85a0-3437-11e8-9a34-afaf99997127.png)

But upon doing that, I got this error after restarting IntelliJ with the plugin installed:
![image](https://user-images.githubusercontent.com/3081566/38152796-5927eaee-3437-11e8-94a5-6a68517ee549.png)

Is the plugin set to resolve those dependencies automatically?

**Comment by cdietrich** [comment]
The plugin is dead but the old version should work if you installl both the Xtext and the xtend idea plugin

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
