### ISSUE TITLE
Xtend compilation fails (windows platform, default project)

### ISSUE THREAD

**Issue by EricSalemi** [eclipse/xtext-idea#26]
I'm working with:

Windows 7 (64-bits)
Java 1.8.0_112 (64-bits)
IntelliJ IDEA 2016.3.1 (64-bits)
XText 2.10.0

Steps to reproduce the issue:

Create an Xtext project with default options (call it "sandbox")
Build the "sandbox.parent" project
Accept Xtend facet auto-detection

At this point the framework simply fails (once) with the following error:

`Error during auto build.: java.io.IOException: Invalid file name: ':'`

Full error log is [here](https://github.com/eclipse/xtext-idea/files/668546/log.txt).

It seems that all Xtend files have been compiled correctly but I suspect this happened before the error popped up. After that, any modification to an Xtend file in any of the source folder, will trigger the Xtend compiler and a new occurence of the error above. Moreover, changes are not reflected in the compiled java files, which tells me the compilation is broken at that point.

By chance, I happened to manually change the configured output folder in the auto-configured xtend facet. I replaced the absolute path with a relative path and everything worked again magically. I strongly suspect the Xtend compiler to simply fail on the colon ":" character.

Btw, I was already having this issue with Xtext 2.9.2.

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
