### ISSUE TITLE
Disable certain log messages for idea.log

### ISSUE THREAD

**Issue by Treverix** [eclipse/xtext-idea#30]
I see thousands of [INFO] log messages from xtext on idea.log which I'd like to filter out early:

`2017-01-09 13:22:38,454 [12249464]   INFO - uild.XtextAutoBuilderComponent - Skipping module 'a module'. Nothing to do here. 
`

This actually contributes 98 lines/15k chars with a frequency of 200-300ms to the logs and makes it VERY complicated to find 'real' issues. Would it be possible to have a plugin setting to set the xtext log level or change the log level for this message to [DEBUG]?

Another candidate for [DEBUG] level:

`
2017-01-09 13:28:12,087 [ 206388]   INFO - rg.eclipse.xtext.build.Indexer - Creating Deltas for changes. Deleted : [], Changed : [  <list of changed files> ]. 
`

Cheers,
Andreas

---

Intellij 2016.3.2
xtext 2.10

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
