### ISSUE TITLE
java.lang.AssertionError: Wrong line separators: '...ceState) {\r\n\tthrow n...'

### ISSUE THREAD

**Issue by programadorthi** [eclipse/xtext-idea#34]
I created a MainActivity. When I write `override onCreate` and press enter, the method is not overrided and throw Assertion Error.

[idea.txt](https://github.com/eclipse/xtext-idea/files/708756/idea.txt)

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
