### ISSUE TITLE
Suppress calling doCleanBuild() when refresh all Gradle projects

### ISSUE THREAD

**Issue by frami** [eclipse/xtext-idea#36]
I added a org.eclipse.xtext.generator.IFilePostProcessor which handles some protected regions in the generated files. The problem is now, when I click the "Refresh all Gradle projects" button in IntelliJ, the doCleanBuild() method in the XtextAutoBuilderComponent class is called. Is there a possibility to suppress this behavior?

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
