### ISSUE TITLE
Idea workspace die after an unsuccessful attempt to save data with xtext index.

### ISSUE THREAD

**Issue by ArchCC** [eclipse/xtext-idea#9]
Seems like dsl plugin generate and store some index in workspace.xml, which used by Idea project. In my case this info contain 19Mb of data... which seem too big in compare with 47Kb of empty project... which lead to "Unable to save settings" and project with empty workspace.xml (all settings reset)

```
<component name="XtextAutoBuilderState">
    <installedLanguages>mydsl;xtend;xtext</installedLanguages>
    <index>***<index>
    <module2generated>***</module2generated>
</component>
```

**Comment by didos36** [comment]
I have exactly same case. Do you know any workaround?

**Comment by ArchCC** [comment]
Nop, just backup my workspace.xml...

**Comment by cdietrich** [comment]
as xtext-idea is obsolete: wontfix
